name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Test
      run: |
        # create and start virtual environment
        python3 -m venv venv
        source venv/bin/activate
        # Install dependencies
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Test with pytest
        pytest
        # Stop virtual environment
        source venv/bin/deactivate
